table Dim_Calendario
	lineageTag: 8dc19847-6725-41a0-9732-22e11e0af505

	column Fecha
		dataType: dateTime
		formatString: Long Date
		lineageTag: 2f9bd183-d0a3-4f4b-ab7d-e9ec81c9758f
		summarizeBy: none
		sourceColumn: Fecha

		variation Variación
			isDefault
			relationship: fa9f2ce7-51a1-4ee0-bf19-d7c9aa244e0f
			defaultHierarchy: LocalDateTable_e616acb1-b562-4fe9-82dc-09b5abddb4b3.'Jerarquía de fechas'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column Año
		dataType: int64
		formatString: 0
		lineageTag: 5e9d07b4-e9dc-4423-86a8-f56c8e15ac9f
		summarizeBy: sum
		sourceColumn: Año

		annotation SummarizationSetBy = Automatic

	column Semana
		dataType: int64
		formatString: 0
		lineageTag: 3256064d-0194-4a3b-b79b-8c4c3883f6b0
		summarizeBy: sum
		sourceColumn: Semana

		annotation SummarizationSetBy = Automatic

	column Mes
		dataType: string
		lineageTag: 9a1a59c0-3dcf-4e18-9830-ff7131ae4cd1
		summarizeBy: none
		sourceColumn: Mes

		annotation SummarizationSetBy = Automatic

	column 'Numero Mes'
		dataType: int64
		formatString: 0
		lineageTag: c4abbc65-9aa6-4047-9272-e9b77b746d9f
		summarizeBy: sum
		sourceColumn: Numero Mes

		annotation SummarizationSetBy = Automatic

	column datekey
		dataType: int64
		formatString: 0
		lineageTag: 4694e59c-0fa7-43ab-83c3-b3e26b5f9d63
		summarizeBy: none
		sourceColumn: datekey

		annotation SummarizationSetBy = Automatic

	partition Dim_Calendario = m
		mode: import
		source =
				let
				    Origen = Excel.Workbook(File.Contents("C:\Users\Diego\Downloads\VentasVehiculos (1).xlsx"), null, true),
				    Dim_Calendario_Table = Origen{[Item="Dim_Calendario",Kind="Table"]}[Data],
				    #"Tipo cambiado" = Table.TransformColumnTypes(Dim_Calendario_Table,{{"Fecha", type date}, {"Año", Int64.Type}, {"Semana", Int64.Type}, {"Mes", type text}, {"Numero Mes", Int64.Type}, {"datekey", Int64.Type}})
				in
				    #"Tipo cambiado"

	annotation PBI_ResultType = Table

