table Hoja1
	lineageTag: 5f71800a-841c-47ec-b6da-24761c7b7dc4

	column Fecha
		dataType: dateTime
		formatString: Long Date
		lineageTag: beeb2564-bca6-4dff-a621-ee25c9638cfe
		summarizeBy: none
		sourceColumn: Fecha

		variation Variación
			isDefault
			relationship: d7da9f3d-096d-486b-a72b-4b2771da2175
			defaultHierarchy: LocalDateTable_d182b456-efa2-4d33-b60a-8c729af3bb56.'Jerarquía de fechas'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column Año
		dataType: int64
		formatString: 0
		lineageTag: e3c061ef-1abb-460f-9b1b-933aba643d76
		summarizeBy: sum
		sourceColumn: Año

		annotation SummarizationSetBy = Automatic

	column Semana
		dataType: int64
		formatString: 0
		lineageTag: 5081bd59-3715-4e9a-9443-a0b8ad9fba2f
		summarizeBy: sum
		sourceColumn: Semana

		annotation SummarizationSetBy = Automatic

	column Mes
		dataType: string
		lineageTag: 99e0e4ad-0203-40dc-8168-359584fa5353
		summarizeBy: none
		sourceColumn: Mes

		annotation SummarizationSetBy = Automatic

	column 'Numero Mes'
		dataType: int64
		formatString: 0
		lineageTag: 66becbd6-e14d-48d6-a3e3-942c841fee64
		summarizeBy: sum
		sourceColumn: Numero Mes

		annotation SummarizationSetBy = Automatic

	column datekey
		dataType: int64
		formatString: 0
		lineageTag: d4c4935b-9da6-4540-bf07-bd3c5e13282b
		summarizeBy: none
		sourceColumn: datekey

		annotation SummarizationSetBy = Automatic

	column Column7
		dataType: string
		lineageTag: f6795190-1aab-42c7-8199-482bdfefbf7a
		summarizeBy: none
		sourceColumn: Column7

		annotation SummarizationSetBy = Automatic

	column id_canal
		dataType: int64
		formatString: 0
		lineageTag: f9d691e5-d1da-41a9-9bd5-b7c3470fcf09
		summarizeBy: none
		sourceColumn: id_canal

		annotation SummarizationSetBy = Automatic

	column tipo_canal
		dataType: string
		lineageTag: bc89ea57-0744-49e5-a01f-b8e35c8f5593
		summarizeBy: none
		sourceColumn: tipo_canal

		annotation SummarizationSetBy = Automatic

	column canal
		dataType: string
		lineageTag: 3afc1274-0fd0-4782-92d8-dfe4ad465805
		summarizeBy: none
		sourceColumn: canal

		annotation SummarizationSetBy = Automatic

	column Column11
		dataType: string
		lineageTag: d7204dfa-1959-4ad9-8152-670d5ed652bb
		summarizeBy: none
		sourceColumn: Column11

		annotation SummarizationSetBy = Automatic

	column id_sede
		dataType: int64
		formatString: 0
		lineageTag: 646505d4-d92a-4042-8915-a97fcf7f1b86
		summarizeBy: none
		sourceColumn: id_sede

		annotation SummarizationSetBy = Automatic

	column nombre_sede
		dataType: string
		lineageTag: 53464c2c-90b1-43c9-a3ee-e14dfdb90ecf
		summarizeBy: none
		sourceColumn: nombre_sede

		annotation SummarizationSetBy = Automatic

	column ubicacion_sede
		dataType: string
		lineageTag: 58dddc1f-adca-4bf3-b15a-dab5cbe45145
		summarizeBy: none
		sourceColumn: ubicacion_sede

		annotation SummarizationSetBy = Automatic

	column Column15
		dataType: string
		lineageTag: aeeddd29-5758-495f-8600-2a5d1c4dcf59
		summarizeBy: none
		sourceColumn: Column15

		annotation SummarizationSetBy = Automatic

	column id_Cliente
		dataType: int64
		formatString: 0
		lineageTag: 978f38bf-0465-46f5-8226-739b91663cdc
		summarizeBy: none
		sourceColumn: id_Cliente

		annotation SummarizationSetBy = Automatic

	column Nombre
		dataType: string
		lineageTag: 5d835199-4807-4514-8960-05d1685b63e4
		summarizeBy: none
		sourceColumn: Nombre

		annotation SummarizationSetBy = Automatic

	column Column18
		dataType: string
		lineageTag: 116a8d04-5556-47ab-8a46-25041a5d431d
		summarizeBy: none
		sourceColumn: Column18

		annotation SummarizationSetBy = Automatic

	column id_vehiculo
		dataType: int64
		formatString: 0
		lineageTag: 00bc02d8-3cda-4b9b-9b5d-6f33f6b7c70a
		summarizeBy: none
		sourceColumn: id_vehiculo

		annotation SummarizationSetBy = Automatic

	column marca_vehiculo
		dataType: string
		lineageTag: 43e4de7c-ec5b-46d3-b7b3-07fc56495553
		summarizeBy: none
		sourceColumn: marca_vehiculo

		annotation SummarizationSetBy = Automatic

	column modelo_vehiculo
		dataType: string
		lineageTag: e2c7e857-a091-4c23-8951-584d35967e8b
		summarizeBy: none
		sourceColumn: modelo_vehiculo

		annotation SummarizationSetBy = Automatic

	column tipo_vehiculo
		dataType: string
		lineageTag: 5c157e46-577c-4014-bf15-a2be40eb51eb
		summarizeBy: none
		sourceColumn: tipo_vehiculo

		annotation SummarizationSetBy = Automatic

	column año_vehiculo
		dataType: int64
		formatString: 0
		lineageTag: feaa39c8-7779-472a-ac3f-a9e1e645501e
		summarizeBy: sum
		sourceColumn: año_vehiculo

		annotation SummarizationSetBy = Automatic

	column Column24
		dataType: string
		lineageTag: 90a74c05-9746-489b-a6b9-01eba77a1b67
		summarizeBy: none
		sourceColumn: Column24

		annotation SummarizationSetBy = Automatic

	column periodo
		dataType: int64
		formatString: 0
		lineageTag: b91f5ca9-8823-400b-8880-ba5efa5c5dfb
		summarizeBy: sum
		sourceColumn: periodo

		annotation SummarizationSetBy = Automatic

	column 'mes.1'
		dataType: string
		lineageTag: e8654e57-1dfa-4202-ae44-cc1c4aa0761b
		summarizeBy: none
		sourceColumn: mes.1

		annotation SummarizationSetBy = Automatic

	column id_sede_1
		dataType: int64
		formatString: 0
		lineageTag: 1d3a6280-c268-45e1-86eb-4696cdd86b6f
		summarizeBy: sum
		sourceColumn: id_sede_1

		annotation SummarizationSetBy = Automatic

	column ppto
		dataType: int64
		formatString: 0
		lineageTag: 37d1dd06-85f5-44db-ba22-eb80f007c6a2
		summarizeBy: sum
		sourceColumn: ppto

		annotation SummarizationSetBy = Automatic

	column Column29
		dataType: string
		lineageTag: 635f2769-16b6-4c95-8d0a-726de0bbc756
		summarizeBy: none
		sourceColumn: Column29

		annotation SummarizationSetBy = Automatic

	column ID
		dataType: int64
		formatString: 0
		lineageTag: 3338b550-8a44-4c83-a20f-e864a78ec801
		summarizeBy: count
		sourceColumn: ID

		annotation SummarizationSetBy = Automatic

	column datekey_2
		dataType: int64
		formatString: 0
		lineageTag: 899f04ae-83f0-4ae3-aa57-d6d41cc5d23e
		summarizeBy: sum
		sourceColumn: datekey_2

		annotation SummarizationSetBy = Automatic

	column 'Canal.1'
		dataType: int64
		formatString: 0
		lineageTag: 990989a2-a7c8-43f8-b3bd-81825817bb1b
		summarizeBy: sum
		sourceColumn: Canal.1

		annotation SummarizationSetBy = Automatic

	column Cliente
		dataType: int64
		formatString: 0
		lineageTag: 13ca5a0a-1026-4f94-98f1-07f02404b8be
		summarizeBy: sum
		sourceColumn: Cliente

		annotation SummarizationSetBy = Automatic

	column Segmento
		dataType: string
		lineageTag: 71d79e7f-d718-4761-ba69-3c79e0a648a4
		summarizeBy: none
		sourceColumn: Segmento

		annotation SummarizationSetBy = Automatic

	column Vehiculo
		dataType: int64
		formatString: 0
		lineageTag: 86b59d56-c92c-4f48-95ee-8a274511adbd
		summarizeBy: sum
		sourceColumn: Vehiculo

		annotation SummarizationSetBy = Automatic

	column 'Costo Vehículo'
		dataType: double
		lineageTag: 58c489ce-54f1-457c-9f08-2cc822b37c15
		summarizeBy: sum
		sourceColumn: Costo Vehículo

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Precio_Venta_sin_IGV
		dataType: double
		lineageTag: 1ca73c67-61ea-4fd3-a577-821b65503686
		summarizeBy: sum
		sourceColumn: Precio_Venta_sin_IGV

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column IGV
		dataType: double
		lineageTag: 1b315f04-11ce-4281-ad89-e3f522be7975
		summarizeBy: sum
		sourceColumn: IGV

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Sede
		dataType: int64
		formatString: 0
		lineageTag: 9c9c8377-778b-4486-b5c5-d9edd3b47fd8
		summarizeBy: sum
		sourceColumn: Sede

		annotation SummarizationSetBy = Automatic

	column Vendedor
		dataType: int64
		formatString: 0
		lineageTag: 1f9b9f06-efeb-4eb7-b990-7211398e2dd0
		summarizeBy: sum
		sourceColumn: Vendedor

		annotation SummarizationSetBy = Automatic

	column Column41
		dataType: string
		lineageTag: ca0f407f-5b39-4726-a704-0061c5969713
		summarizeBy: none
		sourceColumn: Column41

		annotation SummarizationSetBy = Automatic

	column 'Id.1'
		dataType: int64
		formatString: 0
		lineageTag: 74e180b0-f584-4d19-85b4-9c188807257d
		summarizeBy: sum
		sourceColumn: Id.1

		annotation SummarizationSetBy = Automatic

	column Modelo
		dataType: string
		lineageTag: 88f72a51-6009-4aa9-b75b-1b4176641ec2
		summarizeBy: none
		sourceColumn: Modelo

		annotation SummarizationSetBy = Automatic

	column Version
		dataType: string
		lineageTag: e07274e5-ea75-4119-a1f9-526dca41fddf
		summarizeBy: none
		sourceColumn: Version

		annotation SummarizationSetBy = Automatic

	column Precio
		dataType: int64
		formatString: 0
		lineageTag: 388a301e-5534-48f9-ad6f-0dc0850c0660
		summarizeBy: sum
		sourceColumn: Precio

		annotation SummarizationSetBy = Automatic

	column Imagen
		dataType: string
		lineageTag: 9b887a91-c307-4039-bdc6-a3a53e9f92f5
		summarizeBy: none
		sourceColumn: Imagen

		annotation SummarizationSetBy = Automatic

	column Column47
		dataType: string
		lineageTag: 02bd33bb-2d8e-4b2b-8926-48d084488c1b
		summarizeBy: none
		sourceColumn: Column47

		annotation SummarizationSetBy = Automatic

	column ID_Vendedor
		dataType: int64
		formatString: 0
		lineageTag: d4bfaba7-552d-486d-8b08-fd1ead4ed932
		summarizeBy: none
		sourceColumn: ID_Vendedor

		annotation SummarizationSetBy = Automatic

	column Vendedor_3
		dataType: string
		lineageTag: d476a788-8ea5-478f-85be-17c1a9b06c88
		summarizeBy: none
		sourceColumn: Vendedor_3

		annotation SummarizationSetBy = Automatic

	column fecha_nacimiento
		dataType: dateTime
		formatString: General Date
		lineageTag: 4f4141b6-4f5e-4e6c-a877-86e16a6a4d12
		summarizeBy: none
		sourceColumn: fecha_nacimiento

		variation Variación
			isDefault
			relationship: 22f1315a-8c57-4679-b92d-84824709648f
			defaultHierarchy: LocalDateTable_740e6342-ae12-4f9b-8bb2-afc7d40231d9.'Jerarquía de fechas'

		annotation SummarizationSetBy = Automatic

	column Foto
		dataType: string
		lineageTag: 4051b846-e182-43ef-9253-72eea92aeff2
		summarizeBy: none
		sourceColumn: Foto

		annotation SummarizationSetBy = Automatic

	partition Hoja1 = m
		mode: import
		source =
				let
				    Origen = Excel.Workbook(File.Contents("C:\Users\Diego\Downloads\VentasVehiculos (1).xlsx"), null, true),
				    Hoja1_Sheet = Origen{[Item="Hoja1",Kind="Sheet"]}[Data],
				    #"Encabezados promovidos" = Table.PromoteHeaders(Hoja1_Sheet, [PromoteAllScalars=true]),
				    #"Tipo cambiado" = Table.TransformColumnTypes(#"Encabezados promovidos",{{"Fecha", type date}, {"Año", Int64.Type}, {"Semana", Int64.Type}, {"Mes", type text}, {"Numero Mes", Int64.Type}, {"datekey", Int64.Type}, {"Column7", type any}, {"id_canal", Int64.Type}, {"tipo_canal", type text}, {"canal", type text}, {"Column11", type any}, {"id_sede", Int64.Type}, {"nombre_sede", type text}, {"ubicacion_sede", type text}, {"Column15", type any}, {"id_Cliente", Int64.Type}, {"Nombre", type text}, {"Column18", type any}, {"id_vehiculo", Int64.Type}, {"marca_vehiculo", type text}, {"modelo_vehiculo", type text}, {"tipo_vehiculo", type text}, {"año_vehiculo", Int64.Type}, {"Column24", type any}, {"periodo", Int64.Type}, {"mes", type text}, {"id_sede_1", Int64.Type}, {"ppto", Int64.Type}, {"Column29", type any}, {"ID", Int64.Type}, {"datekey_2", Int64.Type}, {"Canal", Int64.Type}, {"Cliente", Int64.Type}, {"Segmento", type text}, {"Vehiculo", Int64.Type}, {"Costo Vehículo", type number}, {"Precio Venta sin IGV", type number}, {"IGV", type number}, {"Sede", Int64.Type}, {"Vendedor", Int64.Type}, {"Column41", type any}, {"Id", Int64.Type}, {"Modelo", type text}, {"Version", type text}, {"Precio", Int64.Type}, {"Imagen", type text}, {"Column47", type any}, {"ID_Vendedor", Int64.Type}, {"Vendedor_3", type text}, {"fecha_nacimiento", type datetime}, {"Foto", type text}}),
				    #"Columnas con nombre cambiado" = Table.RenameColumns(#"Tipo cambiado",{{"mes", "mes.1"}, {"Canal", "Canal.1"}, {"Id", "Id.1"}, {"Precio Venta sin IGV", "Precio_Venta_sin_IGV"}})
				in
				    #"Columnas con nombre cambiado"

	annotation PBI_ResultType = Table

